### ISSUE TITLE
Add to maven central repository

### ISSUE THREAD

**Issue by greenlaw110** [archiecobbs/nvt4j#2]
can't get nvt4j through maven central repository prevent us from using it in our open source project

**Comment by archiecobbs** [comment]
I understand - I was in the same boat. This project is my own copy of the original defunct project from googlecode. I had to copy it so I could fix a bug.

Publishing to maven would require refactoring the code to put it into a legitimate package, e.g. under `org.dellroad`.

**Comment by archiecobbs** [comment]
Release 1.2.0 now added to Maven Central. Allow a few hours for the new module to show up.

Note that all classes have been repackaged under `org.dellroad.nvt4j`.
